### ISSUE TITLE
Don't find Duplicated Unique ID if GameObject is not active

### ISSUE THREAD

**Issue by GorlikItsMe** [ashblue/fluid-unique-id#25]
I made 2 duplicated GameObjects
But when I use Repair Window to find it, it shows nothing.
I figured out it not find GameObject if it is not active on the Scene.

I use 1.0.2 version

**Comment by ashblue** [comment]
Did you save the scene before running the repair? It can sometimes cause problems if you don't.

**Comment by ashblue** [comment]
Closing as I haven't seen this issue. If it comes up again I'll re-open the ticket.
